version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapiServer
    ports:
      - "8000:8000"
    volumes:
      - .:/invisibledatahand:delegated
    env_file:
      - .env
    environment:
      - ENV=development
      - PYTHONDONTWRITEBYTECODE=1
      - AWS_ENDPOINT_URL=http://localstack:4566
    command: fastapi run server/main.py --port 8000 --reload
    depends_on:
      - localstack

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: reactClient
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DEFAULT_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./localstack-data:/var/lib/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-script.sh
