name: Auto Assign

on:
  pull_request:
    types: [opened] 

jobs:
  assign-pr-creator:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
    - name: 'Auto-assign PR creator'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}

